name: PR Check Workflow

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PR checking
        run: echo "PR check running for branch: ${{ github.head_ref }}"
